// Code generated by "stringer -type=Importance"; DO NOT EDIT

package cabot

import "fmt"

const _Importance_name = "WARNINGERRORCRITICAL"

var _Importance_index = [...]uint8{0, 7, 12, 20}

func (i Importance) String() string {
	i -= 1
	if i >= Importance(len(_Importance_index)-1) {
		return fmt.Sprintf("Importance(%d)", i+1)
	}
	return _Importance_name[_Importance_index[i]:_Importance_index[i+1]]
}
