// generated by jsonenums -type=Status; DO NOT EDIT

package cabot

import (
	"encoding/json"
	"fmt"
)

var (
	_StatusNameToValue = map[string]Status{
		"passing":      passing,
		"intermittent": intermittent,
		"failing":      failing,
	}

	_StatusValueToName = map[Status]string{
		passing:      "passing",
		intermittent: "intermittent",
		failing:      "failing",
	}
)

func init() {
	var v Status
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_StatusNameToValue = map[string]Status{
			interface{}(passing).(fmt.Stringer).String():      passing,
			interface{}(intermittent).(fmt.Stringer).String(): intermittent,
			interface{}(failing).(fmt.Stringer).String():      failing,
		}
	}
}

// MarshalJSON is generated so Status satisfies json.Marshaler.
func (r Status) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _StatusValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Status: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Status satisfies json.Unmarshaler.
func (r *Status) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Status should be a string, got %s", data)
	}
	v, ok := _StatusNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Status %q", s)
	}
	*r = v
	return nil
}
